GO

/*Create Database */
CREATE DATABASE StaffPortalDB

GO

/*Create Table */
USE [StaffPortalDB]

CREATE TABLE APP_GENDER
(
GENDER_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[GENDER_DESCRIPTION] VARCHAR(20) NOT NULL
)

CREATE TABLE APP_QUALIFICATION
(
[QUALIFICATION_ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[QUALIFICATION_LEVEL] INT NOT NULL,
[QUALIFICATION_DESCRIPTION] VARCHAR(50) NOT NULL
)

GO

CREATE TABLE APP_STAFF
(
STAFF_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[EMPLOYMENT_NUMBER] VARCHAR(20) NOT NULL,
[FIRST_NAME] VARCHAR(50) NOT NULL,
[LAST_NAME] VARCHAR(50) NOT NULL,
[BIRTH_DATE] DATE NOT NULL,
[SALARY] DECIMAL(10,2) NOT NULL,
[YEARS_WORK_EXPERIENCE] INT NOT NULL,
[GENDER_ID] INT NOT NULL FOREIGN KEY REFERENCES APP_GENDER(GENDER_ID) ,
[QUALIFICATION_ID] INT NOT NULL FOREIGN KEY REFERENCES APP_QUALIFICATION(QUALIFICATION_ID),
)

GO

/*Populate Values*/

INSERT INTO APP_GENDER([GENDER_DESCRIPTION])
VALUES ('Male'),('Female')

INSERT INTO APP_QUALIFICATION(QUALIFICATION_LEVEL,QUALIFICATION_DESCRIPTION)
VALUES (5,'Diploma'),(6,'Degree'),(7,'Post Graduate'),(8,'Masters Degree')

GO

PRINT 'Happy Script!'

